-- INTEGRATIONS
USE ROLE ACCOUNTADMIN;
SHOW INTEGRATIONS;
SHOW STAGES IN SCHEMA MASTERCLASS.PUBLIC;
DESC STAGE MASTERCLASS.PUBLIC.AZURE_STAGE;

USE ROLE ACCOUNTADMIN;

CREATE STORAGE INTEGRATION MASTERCLASS_AZURE
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '<CHANGE_ME>'
  STORAGE_ALLOWED_LOCATIONS = ('azure://dbxdl.blob.core.windows.net/demo/');

DESC STORAGE INTEGRATION MASTERCLASS_AZURE;

SELECT
  SYSTEM$VALIDATE_STORAGE_INTEGRATION(
    'MASTERCLASS_AZURE',
    'azure://dbxdl.blob.core.windows.net/demo/',
    'validate_all.txt', 'all');

DESC INTEGRATION MASTERCLASS_AZURE;

-- RBAC
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION MASTERCLASS_AZURE TO ROLE SYSADMIN;

------------------------- CODE -------------------------

CREATE OR REPLACE VIEW CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER;

CREATE OR REPLACE VIEW CUSTOMER_DEMOGRAPHICS AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_DEMOGRAPHICS;

CREATE OR REPLACE VIEW DATE_DIM AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM;

CREATE OR REPLACE VIEW ITEM AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM;

CREATE OR REPLACE VIEW STORE AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE;

CREATE OR REPLACE VIEW STORE_SALES AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES;


------------------------- CODE -------------------------
USE ROLE SYSADMIN;
USE DATABASE SNOWFLAKE_CODE_SAMPLE;
USE SCHEMA SNOWFLAKE_CODE_SAMPLE.TPCDS_SF10TCL;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FILE_FORMAT
 TYPE = PARQUET 
 COMPRESSION = SNAPPY
 USE_VECTORIZED_SCANNER = TRUE;

-- CUSTOMER
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER;

CREATE STAGE IF NOT EXISTS semantic_customer
 STORAGE_INTEGRATION = MASTERCLASS_AZURE
 URL = 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/customer/'
 COMMENT = 'Lineitems data stage Azure';

COPY INTO 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/customer/'
FROM (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER
)
STORAGE_INTEGRATION = MASTERCLASS_AZURE
FILE_FORMAT = PARQUET_FILE_FORMAT
HEADER = TRUE
MAX_FILE_SIZE = 128000000;

-- CUSTOMER_DEMOGRAPHICS
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_DEMOGRAPHICS;

CREATE STAGE IF NOT EXISTS SEMANTIC_CUSTOMER_DEMOGRAPHICS
 STORAGE_INTEGRATION = MASTERCLASS_AZURE
 URL = 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/customer_demographics/'
 COMMENT = 'Customer Demographics data stage Azure';

COPY INTO 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/customer_demographics/'
FROM (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER_DEMOGRAPHICS
)
STORAGE_INTEGRATION = MASTERCLASS_AZURE
FILE_FORMAT = PARQUET_FILE_FORMAT
HEADER = TRUE
MAX_FILE_SIZE = 128000000;

-- DATE_DIM
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM;

CREATE STAGE IF NOT EXISTS SEMANTIC_DATE_DIM
 STORAGE_INTEGRATION = MASTERCLASS_AZURE
 URL = 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/date_dim/'
 COMMENT = 'Date Dim data stage Azure';

COPY INTO 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/date_dim/'
FROM (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM
)
STORAGE_INTEGRATION = MASTERCLASS_AZURE
FILE_FORMAT = PARQUET_FILE_FORMAT
HEADER = TRUE
MAX_FILE_SIZE = 128000000;

-- ITEM
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM;

CREATE STAGE IF NOT EXISTS SEMANTIC_ITEM
 STORAGE_INTEGRATION = MASTERCLASS_AZURE
 URL = 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/item/'
 COMMENT = 'Item data stage Azure';

COPY INTO 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/item/'
FROM (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM
)
STORAGE_INTEGRATION = MASTERCLASS_AZURE
FILE_FORMAT = PARQUET_FILE_FORMAT
HEADER = TRUE
MAX_FILE_SIZE = 128000000;

-- STORE
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE;

CREATE STAGE IF NOT EXISTS SEMANTIC_STORE
 STORAGE_INTEGRATION = MASTERCLASS_AZURE
 URL = 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/store/'
 COMMENT = 'Store data stage Azure';

COPY INTO 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/store/'
FROM (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE
)
STORAGE_INTEGRATION = MASTERCLASS_AZURE
FILE_FORMAT = PARQUET_FILE_FORMAT
HEADER = TRUE
MAX_FILE_SIZE = 128000000;

-- STORE_SALES
SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES;

CREATE STAGE IF NOT EXISTS SEMANTIC_STORE_SALES
 STORAGE_INTEGRATION = MASTERCLASS_AZURE
 URL = 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/store_sales/'
 COMMENT = 'Store Sales data stage Azure';

COPY INTO 'azure://dbxdl.blob.core.windows.net/demo/cortexsearch_genie/store_sales/'
FROM (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES SAMPLE (0.243) SEED(42)
)
STORAGE_INTEGRATION = MASTERCLASS_AZURE
FILE_FORMAT = PARQUET_FILE_FORMAT
HEADER = TRUE
MAX_FILE_SIZE = 128000000;
